# Auto generated by Kolo at 2024-02-22 16:21:42.272802+00:00.
# Kolo version: 2.19.0
# Django version: 5.0.1
# Trace ID: trc_01HQ8SBDGGMM7JR63HYK66MJYS

import datetime

import time_machine
import httpretty
import json

from django.test import TestCase
from django.utils.http import urlencode

from django.contrib.sessions.models import Session
from event.models import Event
from user.models import User


class MyTestCase(TestCase):
    @httpretty.activate(allow_net_connect=False)
    def test_my_view(self):
        with time_machine.travel("2024-02-22T16:11:06"):
            session, _created = Session.objects.get_or_create(
                session_data=".eJxVjDsOwjAQBe_iGllexx-Wkp4zRLtegwPIluKkQtwdIqWA9s3Me6mR1qWMa8_zOIk6KVCH340pPXLdgNyp3ppOrS7zxHpT9E67vjTJz_Pu_h0U6uVbG2YImawdAnmHnjwCYfQxgHHOJn8VpCNETixpQBTDTsAAiVgK4tT7A80_N7o:1rd7fq:GhLvcn8NkiABdiYv9s4rSIjxtIWAgWB4CWNKQXfVBGU",
                expire_date=datetime.datetime(
                    2024, 3, 7, 11, 55, 34, 717477, tzinfo=datetime.timezone.utc
                ),
                defaults={"session_key": "s932oggdvskdj8gd5uxyjyco38wnoe21"},
            )
            utilisateur, _created = User.objects.get_or_create(
                password="pbkdf2_sha256$720000$fGsJWE0vf9FKfSIrVUv7ux$mzWdmmRJYLoxsqqkJtSAQQdRNKP0CW7LQfvNsLWEs7E=",
                last_login=datetime.datetime(
                    2024, 2, 22, 11, 55, 34, 712476, tzinfo=datetime.timezone.utc
                ),
                is_superuser=True,
                username="Barhamou",
                first_name="",
                last_name="",
                email="hamabarhamou@gmail.com",
                is_staff=True,
                date_joined=datetime.datetime(
                    2024, 1, 24, 18, 44, 18, 459550, tzinfo=datetime.timezone.utc
                ),
                defaults={"id": 1},
            )
            event, _created = Event.objects.get_or_create(
                title="Mini Conference",
                description="Mini Conference djnago",
                date_time=datetime.datetime(
                    2024, 3, 7, 18, 0, tzinfo=datetime.timezone.utc
                ),
                location="Niger",
                image="event_images/niger.jpg",
                category_id=2,
                max_participants=50,
                defaults={"id": 2},
            )
            response = self.client.get(
                "/",
                "",
                HTTP_COOKIE="csrftoken=FkpVcY3wE3FWJ2tOp2BCojGTT0YTHBXX; sessionid=s932oggdvskdj8gd5uxyjyco38wnoe21",
                content_type="text/plain",
            )

            self.assertEqual(response.status_code, 200)
            self.assertTemplateUsed(response, "landing_page.html")

