# Generated by Django 5.0.1 on 2024-01-24 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Category_Evenement",
        ),
    ]
