# Generated by Django 5.0.6 on 2024-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
