# Generated by Django 5.0.6 on 2024-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_emailcampaign_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="message",
            field=models.TextField(),
        ),
    ]
