# Generated by Django 5.0.6 on 2024-05-24 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_emailcampaign_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="message",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
