# Generated by Django 5.0.6 on 2024-05-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_emailcampaign_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
    ]
